"""Package-local constants for IBM watsonx.ai SDK translation."""

WATSONX_INSTRUMENTATION_NAME = "watsonx"
WATSONX_SYSTEM_NAME = "watsonx"

MODEL_INFERENCE_MODULE = "ibm_watsonx_ai.foundation_models.inference"
EMBEDDINGS_MODULE = "ibm_watsonx_ai.foundation_models.embeddings"
MODEL_INFERENCE_CLASS_NAME = "ModelInference"
EMBEDDINGS_CLASS_NAME = "Embeddings"

GENERATE_METHOD_NAME = "generate"
GENERATE_TEXT_METHOD_NAME = "generate_text"
GENERATE_TEXT_STREAM_METHOD_NAME = "generate_text_stream"
AGENERATE_METHOD_NAME = "agenerate"
AGENERATE_STREAM_METHOD_NAME = "agenerate_stream"
CHAT_METHOD_NAME = "chat"
CHAT_STREAM_METHOD_NAME = "chat_stream"
ACHAT_METHOD_NAME = "achat"
ACHAT_STREAM_METHOD_NAME = "achat_stream"

EMBEDDINGS_GENERATE_METHOD_NAME = "generate"
AEMBEDDINGS_GENERATE_METHOD_NAME = "agenerate"
EMBED_QUERY_METHOD_NAME = "embed_query"
EMBED_DOCUMENTS_METHOD_NAME = "embed_documents"
AEMBED_QUERY_METHOD_NAME = "aembed_query"
AEMBED_DOCUMENTS_METHOD_NAME = "aembed_documents"

WATSONX_TEXT_SPAN_NAME = "watsonx.text"
WATSONX_CHAT_SPAN_NAME = "watsonx.chat"
WATSONX_EMBEDDING_SPAN_NAME = "watsonx.embedding"

ASSISTANT_ROLE = "assistant"
USER_ROLE = "user"

CHOICES_KEY = "choices"
CONTENT_KEY = "content"
DELTA_KEY = "delta"
EMBEDDING_KEY = "embedding"
FUNCTION_KEY = "function"
GENERATED_TEXT_KEY = "generated_text"
INPUT_TOKEN_COUNT_KEY = "input_token_count"
MESSAGE_KEY = "message"
MODEL_ID_KEY = "model_id"
NAME_KEY = "name"
PROMPT_TOKENS_KEY = "prompt_tokens"
COMPLETION_TOKENS_KEY = "completion_tokens"
TOTAL_TOKENS_KEY = "total_tokens"
RESULTS_KEY = "results"
ROLE_KEY = "role"
TEXT_KEY = "text"
TOOL_CALLS_KEY = "tool_calls"
TYPE_KEY = "type"
USAGE_KEY = "usage"
GENERATED_TOKEN_COUNT_KEY = "generated_token_count"

FUNCTION_TOOL_TYPE = "function"
