"""LangChain instrumentation constants."""

from respan_sdk.constants.span_attributes import RESPAN_METADATA

LANGCHAIN_RUN_ID_ATTR = "langchain.run_id"
LANGCHAIN_PARENT_RUN_ID_ATTR = "langchain.parent_run_id"
LANGCHAIN_TAGS_ATTR = "langchain.tags"
LANGCHAIN_METADATA_ATTR = "langchain.metadata"
LANGCHAIN_SERIALIZED_ATTR = "langchain.serialized"
LANGCHAIN_FRAMEWORK_ATTR = f"{RESPAN_METADATA}.framework"
LANGCHAIN_RETRY_COUNT_ATTR = "langchain.retry_count"
LANGCHAIN_RETRY_STATE_ATTR = "langchain.retry_state"

LANGCHAIN_MESSAGE_ROLE_MAP = {
    "ai": "assistant",
    "human": "user",
    "chat": "user",
    "system": "system",
    "tool": "tool",
    "function": "tool",
}
LANGCHAIN_ASSISTANT_ROLE = "assistant"
LANGCHAIN_USER_ROLE = "user"
LANGCHAIN_UNKNOWN_ROLE = "unknown"

LANGCHAIN_ID_KEY = "id"
LANGCHAIN_NAME_KEY = "name"
LANGCHAIN_TYPE_KEY = "type"
LANGCHAIN_ROLE_KEY = "role"
LANGCHAIN_CONTENT_KEY = "content"
LANGCHAIN_TOOL_CALL_ID_KEY = "tool_call_id"
LANGCHAIN_TOOL_CALLS_KEY = "tool_calls"
LANGCHAIN_FUNCTION_CALL_KEY = "function_call"
LANGCHAIN_FUNCTION_KEY = "function"
LANGCHAIN_ARGS_KEY = "args"
LANGCHAIN_ARGUMENTS_KEY = "arguments"
LANGCHAIN_ADDITIONAL_KWARGS_KEY = "additional_kwargs"
LANGCHAIN_KWARGS_KEY = "kwargs"
LANGCHAIN_TOOLS_KEY = "tools"
LANGCHAIN_FUNCTIONS_KEY = "functions"
LANGCHAIN_MODEL_KEY = "model"
LANGCHAIN_MODEL_NAME_KEY = "model_name"
LANGCHAIN_REPO_ID_KEY = "repo_id"
LANGCHAIN_LS_MODEL_NAME_KEY = "ls_model_name"
LANGCHAIN_TOKEN_USAGE_KEY = "token_usage"
LANGCHAIN_USAGE_KEY = "usage"
LANGCHAIN_USAGE_METADATA_KEY = "usage_metadata"
LANGCHAIN_RESPONSE_METADATA_KEY = "response_metadata"
LANGCHAIN_PROMPT_TOKENS_KEY = "prompt_tokens"
LANGCHAIN_COMPLETION_TOKENS_KEY = "completion_tokens"
LANGCHAIN_INPUT_TOKENS_KEY = "input_tokens"
LANGCHAIN_OUTPUT_TOKENS_KEY = "output_tokens"
LANGCHAIN_TOTAL_TOKENS_KEY = "total_tokens"
LANGCHAIN_RUN_ID_KEY = "run_id"
LANGCHAIN_FRAMEWORK_METADATA_KEY = "framework"
LANGCHAIN_OTEL_TRACE_ID_ATTR = "trace_id"
LANGCHAIN_OTEL_SPAN_ID_ATTR = "span_id"

LANGCHAIN_MODEL_DUMP_METHOD = "model_dump"
LANGCHAIN_DICT_METHOD = "dict"
LANGCHAIN_DICT_ATTR = "__dict__"
LANGCHAIN_PAGE_CONTENT_ATTR = "page_content"
LANGCHAIN_METADATA_OBJECT_ATTR = "metadata"
LANGCHAIN_LLM_OUTPUT_ATTR = "llm_output"
LANGCHAIN_GENERATIONS_ATTR = "generations"
LANGCHAIN_MESSAGE_ATTR = "message"
LANGCHAIN_TEXT_ATTR = "text"
LANGCHAIN_TOOL_ATTR = "tool"
LANGCHAIN_TOOL_INPUT_ATTR = "tool_input"
LANGCHAIN_LOG_ATTR = "log"
LANGCHAIN_RETURN_VALUES_ATTR = "return_values"

LANGCHAIN_MESSAGE_ID_FIELDS = (
    LANGCHAIN_ID_KEY,
    LANGCHAIN_NAME_KEY,
    LANGCHAIN_TOOL_CALL_ID_KEY,
)
LANGCHAIN_ADDITIONAL_MESSAGE_FIELDS = (
    LANGCHAIN_TOOL_CALLS_KEY,
    LANGCHAIN_FUNCTION_CALL_KEY,
)
LANGCHAIN_SERIALIZED_NAME_FIELDS = (
    LANGCHAIN_NAME_KEY,
    LANGCHAIN_ID_KEY,
    LANGCHAIN_TYPE_KEY,
)
LANGCHAIN_SERIALIZED_MODEL_FIELDS = (
    LANGCHAIN_MODEL_KEY,
    LANGCHAIN_MODEL_NAME_KEY,
)
LANGCHAIN_SERIALIZED_MODEL_KWARG_FIELDS = (
    LANGCHAIN_MODEL_KEY,
    LANGCHAIN_MODEL_NAME_KEY,
    LANGCHAIN_REPO_ID_KEY,
)
LANGCHAIN_METADATA_MODEL_FIELDS = (
    LANGCHAIN_LS_MODEL_NAME_KEY,
    LANGCHAIN_MODEL_KEY,
    LANGCHAIN_MODEL_NAME_KEY,
)
LANGCHAIN_LLM_OUTPUT_USAGE_FIELDS = (
    LANGCHAIN_TOKEN_USAGE_KEY,
    LANGCHAIN_USAGE_KEY,
    LANGCHAIN_USAGE_METADATA_KEY,
)

LANGCHAIN_CALLBACKS_CONFIG_KEY = "callbacks"
LANGCHAIN_CALLBACK_HANDLERS_ATTR = "handlers"
LANGCHAIN_CALLBACK_ADD_HANDLER_METHOD = "add_handler"
LANGCHAIN_CALLBACK_INHERIT_KWARG = "inherit"

LANGCHAIN_GRAPH_TAG_PREFIX = "graph:"
LANGCHAIN_PREGEL_MARKER = "__pregel"
LANGCHAIN_ENTITY_PATH_SEPARATOR = "."
LANGCHAIN_HASH_SEPARATOR = "|"
LANGCHAIN_PRIVATE_ATTR_PREFIX = "_"
LANGCHAIN_HASH_ENCODING = "utf-8"
LANGCHAIN_JSON_CODE_FENCE_PATTERN = (
    r"^\s*(?P<fence>`{3,}|~{3,})[ \t]*(?P<language>jsonc?)?[ \t]*\r?\n"
    r"(?P<body>.*?)(?:\r?\n)?(?P=fence)\s*$"
)
LANGCHAIN_JSON_CODE_FENCE_BODY_GROUP = "body"
LANGCHAIN_JSON_CODE_FENCE_LANGUAGE_GROUP = "language"

FRAMEWORK_LANGCHAIN = "langchain"
FRAMEWORK_LANGGRAPH = "langgraph"
FRAMEWORK_LANGFLOW = "langflow"

GROUP_LANGFLOW_ROOT_RUNS_KWARG = "group_langflow_root_runs"

LANGCHAIN_CALLBACKS_MANAGER_MODULE = "langchain_core.callbacks.manager"
LANGGRAPH_CALLBACKS_MODULE = "langgraph.callbacks"
LANGGRAPH_CALLBACK_HANDLER_CLASS = "GraphCallbackHandler"
LANGGRAPH_CALLBACK_MANAGER_FUNCTIONS = (
    "get_sync_graph_callback_manager_for_config",
    "get_async_graph_callback_manager_for_config",
)
LANGGRAPH_INTERRUPT_EVENT_NAME = "langgraph.interrupt"
LANGGRAPH_RESUME_EVENT_NAME = "langgraph.resume"

CALLBACK_MANAGER_CONFIGURE_METHOD = "configure"

ZERO_SPAN_ID_FALLBACK = "0000000000000001"

CHAIN_FALLBACK_NAME = "chain"
CHAT_MODEL_FALLBACK_NAME = "chat_model"
LLM_FALLBACK_NAME = "llm"
TOOL_FALLBACK_NAME = LANGCHAIN_TOOL_ATTR
RETRIEVER_FALLBACK_NAME = "retriever"
AGENT_ACTION_FALLBACK_NAME = "agent_action"
AGENT_FINISH_EVENT_NAME = "agent_finish"
