#!/usr/bin/env node
// Assembles the published Respan Claude Code plugin from the monorepo's
// single source-of-truth skill (respan/skills). This mirrors the CLI's
// `generate:skill-refs` step: the skill lives in exactly one place and is
// copied into each distribution (CLI bundle, plugin) at build time. Never
// hand-edit files under plugin/skills/ — they are generated by this script.
import {
  cpSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
  rmSync,
} from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pluginRoot = join(here, '..');
const sharedSkill = join(pluginRoot, '..', 'skills'); // respan/skills (source of truth)
const destSkill = join(pluginRoot, 'skills', 'respan'); // plugin/skills/respan (generated)

// The shared SKILL.md carries no YAML frontmatter (the CLI embeds it as raw
// text). A plugin skill needs a `name` + `description` to be discoverable, so
// we prepend one here without touching the shared source.
const FRONTMATTER = `---
name: respan
description: >-
  Respan for LLM observability. Use to set up tracing or the gateway, manage
  prompts (create/version/deploy), run evals, experiments, and datasets, or
  work with traces and logs. Trigger for any Respan platform task or when
  instrumenting an app to send telemetry to Respan.
---
`;

rmSync(destSkill, { recursive: true, force: true });
mkdirSync(destSkill, { recursive: true });

// references/*.md are copied verbatim — SKILL.md links to them relatively.
cpSync(join(sharedSkill, 'references'), join(destSkill, 'references'), {
  recursive: true,
});

// SKILL.md gets frontmatter prepended, body preserved exactly.
const body = readFileSync(join(sharedSkill, 'SKILL.md'), 'utf8');
writeFileSync(join(destSkill, 'SKILL.md'), FRONTMATTER + '\n' + body);

console.log(`Built plugin skill -> ${destSkill}`);
