"""Aleph Alpha instrumentation constants."""

ALEPH_ALPHA_INSTRUMENTATION_NAME = "aleph-alpha"
ALEPH_ALPHA_SYSTEM_NAME = "alephalpha"

ALEPH_ALPHA_CLIENT_MODULE = "aleph_alpha_client.aleph_alpha_client"
CLIENT_CLASS_NAME = "Client"
ASYNC_CLIENT_CLASS_NAME = "AsyncClient"

OPERATION_CHAT = "chat"
OPERATION_CHAT_STREAM = "chat_stream"
OPERATION_COMPLETE = "complete"
OPERATION_COMPLETE_STREAM = "complete_stream"
OPERATION_EMBED = "embed"
OPERATION_EMBEDDINGS = "embeddings"
OPERATION_SEMANTIC_EMBED = "semantic_embed"
OPERATION_BATCH_SEMANTIC_EMBED = "batch_semantic_embed"
OPERATION_INSTRUCTABLE_EMBED = "instructable_embed"
OPERATION_EVALUATE = "evaluate"
OPERATION_EXPLAIN = "explain"

METHOD_CHAT = "chat"
METHOD_CHAT_WITH_STREAMING = "chat_with_streaming"
METHOD_COMPLETE = "complete"
METHOD_COMPLETE_WITH_STREAMING = "complete_with_streaming"
METHOD_EMBED = "embed"
METHOD_EMBEDDINGS = "embeddings"
METHOD_SEMANTIC_EMBED = "semantic_embed"
METHOD_BATCH_SEMANTIC_EMBED = "batch_semantic_embed"
METHOD_INSTRUCTABLE_EMBED = "instructable_embed"
METHOD_EVALUATE = "evaluate"
METHOD_EXPLAIN = "explain"

REQUEST_KEY = "request"
MODEL_KEY = "model"

CONTENT_KEY = "content"
DATA_KEY = "data"
DIMENSIONS_KEY = "dimensions"
FINISH_REASON_KEY = "finish_reason"
FUNCTION_KEY = "function"
INPUT_KEY = "input"
INSTRUCTION_KEY = "instruction"
MESSAGES_KEY = "messages"
NAME_KEY = "name"
PROMPT_KEY = "prompt"
PROMPTS_KEY = "prompts"
ROLE_KEY = "role"
TEXT_TYPE = "text"
TOOL_CALL_ID_KEY = "tool_call_id"
TOOL_CALLS_KEY = "tool_calls"
TOOLS_KEY = "tools"
TYPE_KEY = "type"
