"""Ollama instrumentation-local constants."""

OLLAMA_INSTRUMENTATION_NAME = "ollama"
OLLAMA_SYSTEM_NAME = "ollama"

OLLAMA_CLIENT_MODULE = "ollama._client"
CLIENT_CLASS_NAME = "Client"
ASYNC_CLIENT_CLASS_NAME = "AsyncClient"

CHAT_METHOD_NAME = "chat"
GENERATE_METHOD_NAME = "generate"
EMBED_METHOD_NAME = "embed"
EMBEDDINGS_METHOD_NAME = "embeddings"

OLLAMA_CHAT_SPAN_NAME = "ollama.chat"
OLLAMA_GENERATE_SPAN_NAME = "ollama.generate"
OLLAMA_EMBED_SPAN_NAME = "ollama.embed"

ASSISTANT_ROLE = "assistant"
USER_ROLE = "user"
SYSTEM_ROLE = "system"
FUNCTION_TOOL_TYPE = "function"

ARGUMENTS_KEY = "arguments"
CONTENT_KEY = "content"
DESCRIPTION_KEY = "description"
EMBEDDING_KEY = "embedding"
EMBEDDINGS_KEY = "embeddings"
EVAL_COUNT_KEY = "eval_count"
FUNCTION_KEY = "function"
ID_KEY = "id"
INPUT_KEY = "input"
MESSAGE_KEY = "message"
MESSAGES_KEY = "messages"
MODEL_KEY = "model"
NAME_KEY = "name"
PARAMETERS_KEY = "parameters"
PROMPT_KEY = "prompt"
PROMPT_EVAL_COUNT_KEY = "prompt_eval_count"
RESPONSE_KEY = "response"
ROLE_KEY = "role"
STREAM_KEY = "stream"
SYSTEM_KEY = "system"
TOOL_CALLS_KEY = "tool_calls"
TOOL_NAME_KEY = "tool_name"
TOOLS_KEY = "tools"
TYPE_KEY = "type"
