"""Pytest instrumentation-local constants."""

from respan_sdk.constants.llm_logging import LOG_TYPE_TASK, LOG_TYPE_WORKFLOW


PYTEST_INSTRUMENTATION_NAME = "pytest"
PYTEST_RUNTIME_PLUGIN_NAME = "respan-pytest-runtime"

ENV_ENABLED = "RESPAN_PYTEST_ENABLED"
ENV_CAPTURE_CONTENT = "RESPAN_PYTEST_CAPTURE_CONTENT"
ENV_WORKFLOW_NAME = "RESPAN_PYTEST_WORKFLOW_NAME"
ENV_EXAMPLE_RUN_ID = "RESPAN_EXAMPLE_RUN_ID"

TASK_LOG_TYPE = LOG_TYPE_TASK
WORKFLOW_LOG_TYPE = LOG_TYPE_WORKFLOW
MAX_ATTRIBUTE_CHARS = 16_000
MAX_COLLECTION_ITEMS = 50
MAX_SERIALIZATION_DEPTH = 8
