"""Vertex AI instrumentation constants."""

VERTEXAI_INSTRUMENTATION_NAME = "vertexai"
VERTEXAI_SYSTEM_NAME = "google"
VERTEXAI_GENERATE_CONTENT_SPAN_NAME = "vertexai.generate_content"
VERTEXAI_CHAT_SPAN_NAME = "vertexai.chat.send_message"

VERTEXAI_GENERATIVE_MODELS_MODULE = "vertexai.generative_models"
GENERATIVE_MODEL_CLASS_NAME = "GenerativeModel"
CHAT_SESSION_CLASS_NAME = "ChatSession"

GENERATE_CONTENT_METHOD_NAME = "generate_content"
GENERATE_CONTENT_ASYNC_METHOD_NAME = "generate_content_async"
SEND_MESSAGE_METHOD_NAME = "send_message"
SEND_MESSAGE_ASYNC_METHOD_NAME = "send_message_async"

ARGS_KEY = "args"
CANDIDATES_KEY = "candidates"
CONTENT_KEY = "content"
FUNCTION_CALL_KEY = "function_call"
FUNCTION_DECLARATIONS_KEY = "function_declarations"
FUNCTION_KEY = "function"
FUNCTION_RESPONSE_KEY = "function_response"
ID_KEY = "id"
NAME_KEY = "name"
PARAMETERS_KEY = "parameters"
PARTS_KEY = "parts"
RESPONSE_KEY = "response"
ROLE_KEY = "role"
TEXT_KEY = "text"
TYPE_KEY = "type"
USAGE_METADATA_KEY = "usage_metadata"

GENERATION_CONFIG_KEY = "generation_config"
TOOLS_KEY = "tools"
TOOL_CONFIG_KEY = "tool_config"
STREAM_KEY = "stream"
SYSTEM_INSTRUCTION_KEY = "system_instruction"

PROMPT_TOKEN_COUNT_KEY = "prompt_token_count"
CANDIDATES_TOKEN_COUNT_KEY = "candidates_token_count"
THOUGHTS_TOKEN_COUNT_KEY = "thoughts_token_count"
TOTAL_TOKEN_COUNT_KEY = "total_token_count"

ASSISTANT_ROLE = "assistant"
FUNCTION_TOOL_TYPE = "function"
MODEL_ROLE = "model"
SYSTEM_ROLE = "system"
TOOL_ROLE = "tool"
USER_ROLE = "user"
