import {
  ATTR_GEN_AI_INPUT_MESSAGES, ATTR_GEN_AI_OUTPUT_MESSAGES,
  ATTR_GEN_AI_SYSTEM_INSTRUCTIONS, ATTR_GEN_AI_TOOL_DEFINITIONS,
  ATTR_GEN_AI_TOOL_CALL_ARGUMENTS, ATTR_GEN_AI_TOOL_CALL_RESULT,
} from "@opentelemetry/semantic-conventions/incubating";
import { SpanAttributes } from "@traceloop/ai-semantic-conventions";
import {
  AI_PROMPT, AI_PROMPT_MESSAGES, AI_PROMPT_TOOLS, AI_PROMPT_TOOL_CHOICE,
  AI_RESPONSE_TEXT, AI_RESPONSE_OBJECT, AI_RESPONSE_TOOL_CALLS,
  AI_TOOL_CALL, AI_TOOL_CALLS, AI_TOOL_CALL_ARGS, AI_TOOL_CALL_RESULT,
  AI_VALUE, AI_VALUES, AI_EMBEDDING, AI_EMBEDDINGS, AI_DOCUMENTS, AI_RANKING,
  AI_EVALUATION_STATE, AI_EVALUATION_QUESTIONS, AI_EVALUATION_ANSWERS,
  type SpanAttributes as Attributes,
} from "./shared.js";

const CONTENT_KEYS = new Set([
  ATTR_GEN_AI_INPUT_MESSAGES, ATTR_GEN_AI_OUTPUT_MESSAGES,
  ATTR_GEN_AI_SYSTEM_INSTRUCTIONS, ATTR_GEN_AI_TOOL_DEFINITIONS,
  ATTR_GEN_AI_TOOL_CALL_ARGUMENTS, ATTR_GEN_AI_TOOL_CALL_RESULT,
  SpanAttributes.TRACELOOP_ENTITY_INPUT, SpanAttributes.TRACELOOP_ENTITY_OUTPUT,
  SpanAttributes.LLM_REQUEST_FUNCTIONS,
  AI_PROMPT, AI_PROMPT_MESSAGES, AI_PROMPT_TOOLS, AI_PROMPT_TOOL_CHOICE,
  AI_RESPONSE_TEXT, AI_RESPONSE_OBJECT, AI_RESPONSE_TOOL_CALLS,
  AI_TOOL_CALL, AI_TOOL_CALLS, AI_TOOL_CALL_ARGS, AI_TOOL_CALL_RESULT,
  AI_VALUE, AI_VALUES, AI_EMBEDDING, AI_EMBEDDINGS, AI_DOCUMENTS, AI_RANKING,
  AI_EVALUATION_STATE, AI_EVALUATION_QUESTIONS, AI_EVALUATION_ANSWERS,
]);

export function stripContentAttributes(attrs: Attributes): void {
  for (const key of Object.keys(attrs)) {
    if (CONTENT_KEYS.has(key) || key.startsWith(`${SpanAttributes.LLM_PROMPTS}.`) ||
        key.startsWith(`${SpanAttributes.LLM_COMPLETIONS}.`)) {
      delete attrs[key];
    }
  }
}
