"""Haystack instrumentation constants."""

from opentelemetry.semconv_ai import SpanAttributes
from respan_sdk.constants.span_attributes import RESPAN_LOG_TYPE

HAYSTACK_INSTRUMENTATION_NAME = "haystack"

HAYSTACK_ASYNC_PIPELINE_MODULE = "haystack.core.pipeline.async_pipeline"
HAYSTACK_COMPONENT_DECORATOR_ATTRIBUTE = "component"
HAYSTACK_COMPONENT_MODULE = "haystack.core.component.component"
HAYSTACK_COMPONENT_REGISTRY_ATTRIBUTE = "registry"
HAYSTACK_PIPELINE_MODULE = "haystack.core.pipeline.pipeline"

HAYSTACK_ASYNC_PIPELINE_CLASS_NAME = "AsyncPipeline"
HAYSTACK_PIPELINE_CLASS_NAME = "Pipeline"

HAYSTACK_COMPONENT_NAME_PARAMETER = "component_name"
HAYSTACK_RUN_ASYNC_GENERATOR_METHOD_NAME = "run_async_generator"
HAYSTACK_RUN_ASYNC_METHOD_NAME = "run_async"
HAYSTACK_RUN_COMPONENT_ASYNC_METHOD_NAME = "_run_component_async"
HAYSTACK_RUN_COMPONENT_METHOD_NAME = "_run_component"
HAYSTACK_RUN_METHOD_NAME = "run"

HAYSTACK_ASYNC_PIPELINE_RUN_SPAN_NAME = "haystack.async_pipeline.run"
HAYSTACK_COMPONENT_RUN_SPAN_NAME = "haystack.component.run"
HAYSTACK_PIPELINE_RUN_SPAN_NAME = "haystack.pipeline.run"
HAYSTACK_NATIVE_SPAN_NAMES = frozenset(
    {
        HAYSTACK_ASYNC_PIPELINE_RUN_SPAN_NAME,
        HAYSTACK_COMPONENT_RUN_SPAN_NAME,
        HAYSTACK_PIPELINE_RUN_SPAN_NAME,
    }
)

HAYSTACK_ASYNC_PIPELINE_RUN_METHOD_SPAN_NAME = "AsyncPipeline.run"
HAYSTACK_ASYNC_PIPELINE_RUN_ASYNC_METHOD_SPAN_NAME = "AsyncPipeline.run_async"
HAYSTACK_ASYNC_PIPELINE_RUN_ASYNC_GENERATOR_METHOD_SPAN_NAME = (
    "AsyncPipeline.run_async_generator"
)
HAYSTACK_PIPELINE_RUN_METHOD_SPAN_NAME = "Pipeline.run"
HAYSTACK_PIPELINE_SPAN_NAMES = frozenset(
    {
        HAYSTACK_ASYNC_PIPELINE_RUN_METHOD_SPAN_NAME,
        HAYSTACK_ASYNC_PIPELINE_RUN_ASYNC_METHOD_SPAN_NAME,
        HAYSTACK_ASYNC_PIPELINE_RUN_ASYNC_GENERATOR_METHOD_SPAN_NAME,
        HAYSTACK_PIPELINE_RUN_METHOD_SPAN_NAME,
    }
)

OPENINFERENCE_HAYSTACK_MODULE = "openinference.instrumentation.haystack"
OPENINFERENCE_HAYSTACK_WRAPPERS_MODULE = (
    "openinference.instrumentation.haystack._wrappers"
)
OPENINFERENCE_HAYSTACK_INSTRUMENTOR_CLASS_NAME = "HaystackInstrumentor"
OPENINFERENCE_TRANSLATOR_CLASS_NAME = "OpenInferenceTranslator"

RESPAN_HAYSTACK_COMPONENT_CONTEXT_VAR_NAME = "respan_haystack_component_run_context"
RESPAN_HAYSTACK_MAIN_COMPONENT_PATCH_FLAG = "_respan_main_component_patch_applied"
RESPAN_HAYSTACK_PIPELINE_CONTEXT_VAR_NAME = "respan_haystack_pipeline_run_context"

HAYSTACK_NATIVE_PROCESSING_ATTRIBUTES = (
    SpanAttributes.TRACELOOP_ENTITY_NAME,
    SpanAttributes.TRACELOOP_ENTITY_PATH,
    SpanAttributes.TRACELOOP_SPAN_KIND,
    SpanAttributes.TRACELOOP_WORKFLOW_NAME,
    RESPAN_LOG_TYPE,
)
