#!/usr/bin/env node
// Assembles the published Respan editor plugins from the monorepo's single
// source-of-truth skill (respan/skills). This mirrors the CLI's
// `generate:skill-refs` step: the skill lives in exactly one place and is
// copied into each distribution (CLI bundle, Claude Code plugin, Cursor
// plugin, ChatGPT plugin) at build time. Never hand-edit files under */skills/respan/ — they
// are generated by this script.
//
//   node scripts/build-plugins.mjs
//
// Every plugin consumes the same SKILL.md, which links to the Respan docs for
// each task (the content lives in the docs, so there are no references/*.md).
// Claude Code, Cursor, and ChatGPT agree on the skill format (a
// `skills/<name>/SKILL.md` with `name` + `description` frontmatter), so the only
// per-target difference today is the destination directory. Add new targets to TARGETS below.
import { mkdirSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, '..'); // respan/
const sharedSkill = join(repoRoot, 'skills'); // respan/skills (source of truth)

// Destinations, relative to the repo root. Each gets a full copy of the skill.
const TARGETS = [
  join(repoRoot, 'claude-plugin', 'skills', 'respan'), // Claude Code
  join(repoRoot, 'cursor-plugin', 'skills', 'respan'), // Cursor
  join(repoRoot, 'chatgpt-plugin', 'skills', 'respan'), // ChatGPT and Codex
];

// SKILL.md carries its own frontmatter (name + description), so every target
// gets the same file, byte for byte.
const skillMd = readFileSync(join(sharedSkill, 'SKILL.md'), 'utf8');

for (const destSkill of TARGETS) {
  rmSync(destSkill, { recursive: true, force: true });
  mkdirSync(destSkill, { recursive: true });

  writeFileSync(join(destSkill, 'SKILL.md'), skillMd);

  console.log(`Built plugin skill -> ${destSkill}`);
}
