#!/usr/bin/env node
// Assembles the published Respan editor plugins from the monorepo's single
// source-of-truth skill (respan/skills). This mirrors the CLI's
// `generate:skill-refs` step: the skill lives in exactly one place and is
// copied into each distribution (CLI bundle, Claude Code plugin, Cursor
// plugin) at build time. Never hand-edit files under */skills/respan/ — they
// are generated by this script.
//
//   node scripts/build-plugins.mjs
//
// Both plugins consume the same SKILL.md and the same references/*.md. Claude
// Code and Cursor agree on the skill format (a `skills/<name>/SKILL.md` with
// `name` + `description` frontmatter), so the only per-target difference today
// is the destination directory. Add new targets to TARGETS below.
import { cpSync, mkdirSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, '..'); // respan/
const sharedSkill = join(repoRoot, 'skills'); // respan/skills (source of truth)

// Destinations, relative to the repo root. Each gets a full copy of the skill.
const TARGETS = [
  join(repoRoot, 'claude-plugin', 'skills', 'respan'), // Claude Code
  join(repoRoot, 'cursor-plugin', 'skills', 'respan'), // Cursor
];

// The shared SKILL.md carries no YAML frontmatter (the CLI embeds it as raw
// text). A plugin skill needs a `name` + `description` to be discoverable, so
// we prepend one here without touching the shared source.
const FRONTMATTER = `---
name: respan
description: >-
  Respan for LLM observability. Use to set up tracing or the gateway, manage
  prompts (create/version/deploy), run evals, experiments, and datasets, or
  work with traces and logs. Trigger for any Respan platform task or when
  instrumenting an app to send telemetry to Respan.
---
`;

// SKILL.md gets frontmatter prepended, body preserved exactly.
const body = readFileSync(join(sharedSkill, 'SKILL.md'), 'utf8');

for (const destSkill of TARGETS) {
  rmSync(destSkill, { recursive: true, force: true });
  mkdirSync(destSkill, { recursive: true });

  // references/*.md are copied verbatim — SKILL.md links to them relatively.
  cpSync(join(sharedSkill, 'references'), join(destSkill, 'references'), {
    recursive: true,
  });

  writeFileSync(join(destSkill, 'SKILL.md'), FRONTMATTER + '\n' + body);

  console.log(`Built plugin skill -> ${destSkill}`);
}
